### PR TITLE
SortBy optimisations

### PR DESCRIPTION
**Pull request by AdamWillden**
@sunesimonsen you may remember me from the knockout-projections fork. I've finally gotten round to splitting out my commits. These are the commits you'd be most interested in and I believe should contain some performance gains. That said I have no way to confirm. Could you see if there is any gain in what I've done?

### CODE REVIEW

**Comment by AdamWillden** [comment]
Sorry, I meant to add this PR should contain no functional changes.

**Comment by sunesimonsen** [comment]
@AdamWillden thanks I'll look at how it performs on our applications and review the code tomorrow.

Kind regards
Sune

**Comment by sunesimonsen** [comment]
Hi again @AdamWillden, in which conditions did you notice the performance gains? I can feel any difference when sorting 16000 contacts, the  tests also runs at the same speed. Are you sure this improves the performance? Other then that, the code seems to be working, but I haven't review it yet. Sorry for being skeptical, performance optimizations often clutters the code, so they should have a valid gain attached to them.

Kind regards
Sune

**Comment by sunesimonsen** [comment]
@AdamWillden don't feel demotivated by me pushing a bit back, I'm just trying to keep the code stable and maintainable. I really appreciate that you took the time to make the PR, but on the other hand I also need to know the improvements from the PR's that I'm merging.

**Comment by AdamWillden** [comment]
@sunesimonsen not at all.

These were changes I **thought** should contain perceivable gains over large collections. I had no way to test such large collections and knew you did. If there's no gains then please don't worry and simply close the PR, I will maintain my code in my fork.

The main change I thought would bring optimisations was the removal of a fair number of inline function instantiations, which incidentally I feel declutters the code. 

One place for performance gains I thought would be during the addQueue processing because the mappingEvaluation is only performed once for the item being added and not for every binary comparison. I think the best way to do test this is to chain sortBy on top of a filter, filter out a number of results and then dynamically disable the filter to add them back in. I assume you have that ability in your code.

In fact I've noticed a change in arrayChange deletionQueue which could in some scenarios have an adverse rather than positive affect over the original. I've just reverted that change to err on the side of caution though I still feel it would be more positive than adverse.

I guess if there's no perceived gains then this is simply code refactoring; that is aside from one behavioral change during arrayChange deletion to provide feedback into the mappingEvaluator that it is being executed for the purposes of searching for the item to delete. My usage for that is explained over  two comments here: https://github.com/One-com/knockout-projections/pull/7#issuecomment-69349942.

**Pull request closed without merging**
